name: Build and deploy

env:
  BASE_DOMAIN: meshkov-demo.pages.dev
  BASE_PATH: /
  DIST_DIR: ./dist
  PAGES_PROJECT: "meshkov-demo"

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Determine branch for deploy
        id: get-branch
        run: |
          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "BRANCH_NAME=main" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUMBER=${{ github.event.number }}
            echo "BRANCH_NAME=pull-request-${PR_NUMBER}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Run build
        run: |
          npm run build

          if [ "${{ github.ref_name }}" = "master" ]; then
            # Keep crawlers for production builds.
            echo "User-Agent: *\nAllow: /" > ${{ env.DIST_DIR }}/robots.txt
          else
            # Disable crawlers for preview builds.
            echo "User-Agent: *\nDisallow: /" > ${{ env.DIST_DIR }}/robots.txt
          fi

      - name: Install Wrangler
        if: github.event.pull_request.head.repo.fork == false
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages
        if: github.event.pull_request.head.repo.fork == false
        run: npx wrangler pages deploy ${{ env.DIST_DIR }} --project-name="${{ env.PAGES_PROJECT }}" --branch ${{ env.BRANCH_NAME }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_WORKERS_ACCOUNT_ID }}

      - name: Add comment to Pull Request
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == false
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview was deployed to: https://${{ env.BRANCH_NAME }}.${{ env.BASE_DOMAIN }}${{ env.BASE_PATH }}`
            })
